id: a7fbe4ba649b421184ae7690c0df8c12
initial_creation_type: ebook
created_at: 30/07/2021
last_modified_at: 25/11/2021
source_metadata:
  title: test
  subtitle: test
  authors:
  - test
  collection: test
  publisher: test
  id: test
  cover: tmphwhtzkc7.jpg
  credit: tmpgrhv3jt7.jpg
